--1
SELECT EMPLOYEE_ID,LAST_NAME,SALARY
FROM HR.EMPLOYEES;

--2
SELECT FIRST_NAME||' '||LAST_NAME AS "사원명", TO_DATE(HIRE_DATE,'YY-MM-DD') AS "입사일", SALARY*12||'원' AS "연봉" ,DEPARTMENT_ID AS "부서코드"
FROM HR.EMPLOYEES;

--3
SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID in (50, 60) or JOB_ID in ('IT_PROG', 'ST_MAN');

--4
SELECT LAST_NAME, HIRE_DATE, JOB_ID
FROM HR.EMPLOYEES
WHERE HIRE_DATE BETWEEN TO_DATE('1997-01-01','YYYY-MM-DD') AND TO_DATE('2008-01-01','YYYY-MM-DD');

--5
SELECT LAST_NAME, SALARY*12 AS "SAL YEAR", COMMISSION_PCT
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT is null;

--6
SELECT LAST_NAME, JOB_ID
FROM HR.EMPLOYEES
WHERE JOB_ID LIKE '%IT%';

--7
SELECT LAST_NAME, EMAIL, PHONE_NUMBER
FROM HR.EMPLOYEES
WHERE (SALARY BETWEEN 1500 AND 5000) AND JOB_ID LIKE 'IT_PROG';

--8
SELECT EMPLOYEE_ID AS "사원번호", FIRST_NAME||' '||LAST_NAME AS "이름", SALARY*12||'달러' AS "연봉"
FROM HR.EMPLOYEES;

--9
SELECT LAST_NAME||' is a '|| JOB_ID as "Employee Detail"
FROM HR.EMPLOYEES;

--10
SELECT FIRST_NAME||' '||LAST_NAME AS "사원명", '$'||SALARY AS "월급", DEPARTMENT_ID as "부서코드"
FROM HR.EMPLOYEES
WHERE (SALARY NOT BETWEEN 2500 AND 3000) AND DEPARTMENT_ID = 90;

--11
SELECT LAST_NAME AS "이름", JOB_ID, SALARY||'원' AS "급여"
FROM HR.EMPLOYEES
WHERE (JOB_ID='SA_REP' OR JOB_ID='AD_PRES') AND SALARY >=15000;

--12
SELECT EMPLOYEE_ID
FROM HR.EMPLOYEES
ORDER BY 1;

--13
SELECT EMPLOYEE_ID, LAST_NAME, HIRE_DATE
FROM HR.EMPLOYEES
WHERE HIRE_DATE BETWEEN TO_DATE('1997-01-01','YYYY-MM-DD')AND TO_DATE('1997-12-31','YYYY-MM-DD');


--14
SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE JOB_ID LIKE '%MAN%';

--15
SELECT LAST_NAME, DEPARTMENT_ID, HIRE_DATE
FROM HR.EMPLOYEES
ORDER BY DEPARTMENT_ID DESC;


--16
SELECT EMPLOYEE_ID, CONCAT(FIRST_NAME,LAST_NAME) AS "NAME", length(CONCAT(FIRST_NAME,LAST_NAME)) AS "LENGTH"
FROM HR.EMPLOYEES
WHERE CONCAT(FIRST_NAME,LAST_NAME) LIKE '%n';


--17
SELECT LAST_NAME, TO_CHAR(HIRE_DATE, 'DD-MM-YYYY')
FROM HR.EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYYMMDD')>20000000;

--18
SELECT EMPLOYEE_ID, LAST_NAME, CASE WHEN SALARY <10000 THEN '초급' WHEN SALARY >=20000 THEN '고급' ELSE '중급' END AS "구분"
FROM HR.EMPLOYEES;

--19
SELECT EMPLOYEE_ID AS "사원번호" ,LAST_NAME AS "사원이름" , SALARY AS "급여", NVL(COMMISSION_PCT,0) AS "커미션", SALARY*12+(SALARY*12*NVL(COMMISSION_PCT,0)) AS "연봉"
FROM HR.EMPLOYEES;

--20
SELECT EMPLOYEE_ID, LAST_NAME, NVL(MANAGER_ID,1000)
FROM HR.EMPLOYEES;